# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#  find the sum of the even-valued terms.


def even_fibo():

    fibo=[0,1]
    sum=0
    for i in range(32):
                fibo.append(fibo[i]+fibo[i+1])

    for item in fibo:
        if item%2==0:
            sum+=item
    return sum


print(even_fibo())

